//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assemblin.BizTalk.InvoDAL.InvoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InvoWS", ConfigurationName="InvoWS.InvoWS_Port")]
    public interface InvoWS_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (CreateAndUpdateProject_Result) of message CreateAndUpdateProject_Result does not match the default value (CreateAndUpdateProject)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/InvoWS:CreateAndUpdateProject", ReplyAction="*")]
        Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProject_Result CreateAndUpdateProject(Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProject request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/InvoWS:CreateAndUpdateProject", ReplyAction="*")]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProject_Result> CreateAndUpdateProjectAsync(Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProject request);
        
        // CODEGEN: Generating message contract since the wrapper name (CreateAndUpdateProjectExtension_Result) of message CreateAndUpdateProjectExtension_Result does not match the default value (CreateAndUpdateProjectExtension)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/InvoWS:CreateAndUpdateProjectExtension", ReplyAction="*")]
        Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProjectExtension_Result CreateAndUpdateProjectExtension(Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProjectExtension request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/InvoWS:CreateAndUpdateProjectExtension", ReplyAction="*")]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProjectExtension_Result> CreateAndUpdateProjectExtensionAsync(Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProjectExtension request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAndUpdateProject", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/InvoWS", IsWrapped=true)]
    public partial class CreateAndUpdateProject {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InvoWS", Order=0)]
        public string inputString;
        
        public CreateAndUpdateProject() {
        }
        
        public CreateAndUpdateProject(string inputString) {
            this.inputString = inputString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAndUpdateProject_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/InvoWS", IsWrapped=true)]
    public partial class CreateAndUpdateProject_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InvoWS", Order=0)]
        public string return_value;
        
        public CreateAndUpdateProject_Result() {
        }
        
        public CreateAndUpdateProject_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAndUpdateProjectExtension", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/InvoWS", IsWrapped=true)]
    public partial class CreateAndUpdateProjectExtension {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InvoWS", Order=0)]
        public string inputString;
        
        public CreateAndUpdateProjectExtension() {
        }
        
        public CreateAndUpdateProjectExtension(string inputString) {
            this.inputString = inputString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAndUpdateProjectExtension_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/InvoWS", IsWrapped=true)]
    public partial class CreateAndUpdateProjectExtension_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InvoWS", Order=0)]
        public string return_value;
        
        public CreateAndUpdateProjectExtension_Result() {
        }
        
        public CreateAndUpdateProjectExtension_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InvoWS_PortChannel : Assemblin.BizTalk.InvoDAL.InvoWS.InvoWS_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvoWS_PortClient : System.ServiceModel.ClientBase<Assemblin.BizTalk.InvoDAL.InvoWS.InvoWS_Port>, Assemblin.BizTalk.InvoDAL.InvoWS.InvoWS_Port {
        
        public InvoWS_PortClient() {
        }
        
        public InvoWS_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InvoWS_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvoWS_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvoWS_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProject_Result Assemblin.BizTalk.InvoDAL.InvoWS.InvoWS_Port.CreateAndUpdateProject(Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProject request) {
            return base.Channel.CreateAndUpdateProject(request);
        }
        
        public string CreateAndUpdateProject(string inputString) {
            Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProject inValue = new Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProject();
            inValue.inputString = inputString;
            Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProject_Result retVal = ((Assemblin.BizTalk.InvoDAL.InvoWS.InvoWS_Port)(this)).CreateAndUpdateProject(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProject_Result> Assemblin.BizTalk.InvoDAL.InvoWS.InvoWS_Port.CreateAndUpdateProjectAsync(Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProject request) {
            return base.Channel.CreateAndUpdateProjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProject_Result> CreateAndUpdateProjectAsync(string inputString) {
            Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProject inValue = new Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProject();
            inValue.inputString = inputString;
            return ((Assemblin.BizTalk.InvoDAL.InvoWS.InvoWS_Port)(this)).CreateAndUpdateProjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProjectExtension_Result Assemblin.BizTalk.InvoDAL.InvoWS.InvoWS_Port.CreateAndUpdateProjectExtension(Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProjectExtension request) {
            return base.Channel.CreateAndUpdateProjectExtension(request);
        }
        
        public string CreateAndUpdateProjectExtension(string inputString) {
            Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProjectExtension inValue = new Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProjectExtension();
            inValue.inputString = inputString;
            Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProjectExtension_Result retVal = ((Assemblin.BizTalk.InvoDAL.InvoWS.InvoWS_Port)(this)).CreateAndUpdateProjectExtension(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProjectExtension_Result> Assemblin.BizTalk.InvoDAL.InvoWS.InvoWS_Port.CreateAndUpdateProjectExtensionAsync(Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProjectExtension request) {
            return base.Channel.CreateAndUpdateProjectExtensionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProjectExtension_Result> CreateAndUpdateProjectExtensionAsync(string inputString) {
            Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProjectExtension inValue = new Assemblin.BizTalk.InvoDAL.InvoWS.CreateAndUpdateProjectExtension();
            inValue.inputString = inputString;
            return ((Assemblin.BizTalk.InvoDAL.InvoWS.InvoWS_Port)(this)).CreateAndUpdateProjectExtensionAsync(inValue);
        }
    }
}
