//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assemblin.BizTalk.InvoDAL.ImdokWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", ConfigurationName="ImdokWS.ImdokWS_Port")]
    public interface ImdokWS_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (GetInvoicePictureCount_Result) of message GetInvoicePictureCount_Result does not match the default value (GetInvoicePictureCount)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:GetInvoicePictureCount", ReplyAction="*")]
        Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePictureCount_Result GetInvoicePictureCount(Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePictureCount request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:GetInvoicePictureCount", ReplyAction="*")]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePictureCount_Result> GetInvoicePictureCountAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePictureCount request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:GetInvoicePicture", ReplyAction="*")]
        Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePicture_Result GetInvoicePicture(Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePicture request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:GetInvoicePicture", ReplyAction="*")]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePicture_Result> GetInvoicePictureAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePicture request);
        
        // CODEGEN: Generating message contract since the wrapper name (CreatePrognosisCC_Result) of message CreatePrognosisCC_Result does not match the default value (CreatePrognosisCC)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:CreatePrognosisCC", ReplyAction="*")]
        Assemblin.BizTalk.InvoDAL.ImdokWS.CreatePrognosisCC_Result CreatePrognosisCC(Assemblin.BizTalk.InvoDAL.ImdokWS.CreatePrognosisCC request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:CreatePrognosisCC", ReplyAction="*")]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.CreatePrognosisCC_Result> CreatePrognosisCCAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.CreatePrognosisCC request);
        
        // CODEGEN: Generating message contract since the wrapper name (SetPrognosisToFixed_Result) of message SetPrognosisToFixed_Result does not match the default value (SetPrognosisToFixed)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:SetPrognosisToFixed", ReplyAction="*")]
        Assemblin.BizTalk.InvoDAL.ImdokWS.SetPrognosisToFixed_Result SetPrognosisToFixed(Assemblin.BizTalk.InvoDAL.ImdokWS.SetPrognosisToFixed request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:SetPrognosisToFixed", ReplyAction="*")]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.SetPrognosisToFixed_Result> SetPrognosisToFixedAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.SetPrognosisToFixed request);
        
        // CODEGEN: Generating message contract since the wrapper name (UpdatePrognosisCC_Result) of message UpdatePrognosisCC_Result does not match the default value (UpdatePrognosisCC)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:UpdatePrognosisCC", ReplyAction="*")]
        Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePrognosisCC_Result UpdatePrognosisCC(Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePrognosisCC request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:UpdatePrognosisCC", ReplyAction="*")]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePrognosisCC_Result> UpdatePrognosisCCAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePrognosisCC request);
        
        // CODEGEN: Generating message contract since the wrapper name (ProcessIPS_Result) of message ProcessIPS_Result does not match the default value (ProcessIPS)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:ProcessIPS", ReplyAction="*")]
        Assemblin.BizTalk.InvoDAL.ImdokWS.ProcessIPS_Result ProcessIPS(Assemblin.BizTalk.InvoDAL.ImdokWS.ProcessIPS request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:ProcessIPS", ReplyAction="*")]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.ProcessIPS_Result> ProcessIPSAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.ProcessIPS request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReleaseHourAcc_Result) of message ReleaseHourAcc_Result does not match the default value (ReleaseHourAcc)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:ReleaseHourAcc", ReplyAction="*")]
        Assemblin.BizTalk.InvoDAL.ImdokWS.ReleaseHourAcc_Result ReleaseHourAcc(Assemblin.BizTalk.InvoDAL.ImdokWS.ReleaseHourAcc request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:ReleaseHourAcc", ReplyAction="*")]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.ReleaseHourAcc_Result> ReleaseHourAccAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.ReleaseHourAcc request);
        
        // CODEGEN: Generating message contract since the wrapper name (CreateSubProjectFromMainProject_Result) of message CreateSubProjectFromMainProject_Result does not match the default value (CreateSubProjectFromMainProject)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:CreateSubProjectFromMainProject", ReplyAction="*")]
        Assemblin.BizTalk.InvoDAL.ImdokWS.CreateSubProjectFromMainProject_Result CreateSubProjectFromMainProject(Assemblin.BizTalk.InvoDAL.ImdokWS.CreateSubProjectFromMainProject request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:CreateSubProjectFromMainProject", ReplyAction="*")]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.CreateSubProjectFromMainProject_Result> CreateSubProjectFromMainProjectAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.CreateSubProjectFromMainProject request);
        
        // CODEGEN: Generating message contract since the wrapper name (UpdatePriceToInvoiceInJob_Result) of message UpdatePriceToInvoiceInJob_Result does not match the default value (UpdatePriceToInvoiceInJob)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:UpdatePriceToInvoiceInJob", ReplyAction="*")]
        Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePriceToInvoiceInJob_Result UpdatePriceToInvoiceInJob(Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePriceToInvoiceInJob request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:UpdatePriceToInvoiceInJob", ReplyAction="*")]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePriceToInvoiceInJob_Result> UpdatePriceToInvoiceInJobAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePriceToInvoiceInJob request);
        
        // CODEGEN: Generating message contract since the wrapper name (UpdateSalesPriceByWageComponent_Result) of message UpdateSalesPriceByWageComponent_Result does not match the default value (UpdateSalesPriceByWageComponent)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:UpdateSalesPriceByWageComponent", ReplyAction="*")]
        Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateSalesPriceByWageComponent_Result UpdateSalesPriceByWageComponent(Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateSalesPriceByWageComponent request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:UpdateSalesPriceByWageComponent", ReplyAction="*")]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateSalesPriceByWageComponent_Result> UpdateSalesPriceByWageComponentAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateSalesPriceByWageComponent request);
        
        // CODEGEN: Generating message contract since the wrapper name (CreateUpdatePrincipalContactPerson_Result) of message CreateUpdatePrincipalContactPerson_Result does not match the default value (CreateUpdatePrincipalContactPerson)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:CreateUpdatePrincipalContactPerso" +
            "n", ReplyAction="*")]
        Assemblin.BizTalk.InvoDAL.ImdokWS.CreateUpdatePrincipalContactPerson_Result CreateUpdatePrincipalContactPerson(Assemblin.BizTalk.InvoDAL.ImdokWS.CreateUpdatePrincipalContactPerson request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:CreateUpdatePrincipalContactPerso" +
            "n", ReplyAction="*")]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.CreateUpdatePrincipalContactPerson_Result> CreateUpdatePrincipalContactPersonAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.CreateUpdatePrincipalContactPerson request);
        
        // CODEGEN: Generating message contract since the wrapper name (AddProjDokToProforma_Result) of message AddProjDokToProforma_Result does not match the default value (AddProjDokToProforma)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:AddProjDokToProforma", ReplyAction="*")]
        Assemblin.BizTalk.InvoDAL.ImdokWS.AddProjDokToProforma_Result AddProjDokToProforma(Assemblin.BizTalk.InvoDAL.ImdokWS.AddProjDokToProforma request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:AddProjDokToProforma", ReplyAction="*")]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.AddProjDokToProforma_Result> AddProjDokToProformaAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.AddProjDokToProforma request);
        
        // CODEGEN: Generating message contract since the wrapper name (UpdateEmployee_Result) of message UpdateEmployee_Result does not match the default value (UpdateEmployee)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:UpdateEmployee", ReplyAction="*")]
        Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateEmployee_Result UpdateEmployee(Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateEmployee request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ImdokWS:UpdateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateEmployee_Result> UpdateEmployeeAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateEmployee request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInvoicePictureCount", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class GetInvoicePictureCount {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public string no;
        
        public GetInvoicePictureCount() {
        }
        
        public GetInvoicePictureCount(string no) {
            this.no = no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInvoicePictureCount_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class GetInvoicePictureCount_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public int return_value;
        
        public GetInvoicePictureCount_Result() {
        }
        
        public GetInvoicePictureCount_Result(int return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvoicePicture {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvoicePicture", Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePictureBody Body;
        
        public GetInvoicePicture() {
        }
        
        public GetInvoicePicture(Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePictureBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS")]
    public partial class GetInvoicePictureBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string no;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int pictureIndex;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string picture;
        
        public GetInvoicePictureBody() {
        }
        
        public GetInvoicePictureBody(string no, int pictureIndex, string picture) {
            this.no = no;
            this.pictureIndex = pictureIndex;
            this.picture = picture;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvoicePicture_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvoicePicture_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePicture_ResultBody Body;
        
        public GetInvoicePicture_Result() {
        }
        
        public GetInvoicePicture_Result(Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePicture_ResultBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS")]
    public partial class GetInvoicePicture_ResultBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool return_value;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string picture;
        
        public GetInvoicePicture_ResultBody() {
        }
        
        public GetInvoicePicture_ResultBody(bool return_value, string picture) {
            this.return_value = return_value;
            this.picture = picture;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePrognosisCC", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class CreatePrognosisCC {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public string strFromImdok;
        
        public CreatePrognosisCC() {
        }
        
        public CreatePrognosisCC(string strFromImdok) {
            this.strFromImdok = strFromImdok;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePrognosisCC_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class CreatePrognosisCC_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public int return_value;
        
        public CreatePrognosisCC_Result() {
        }
        
        public CreatePrognosisCC_Result(int return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetPrognosisToFixed", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class SetPrognosisToFixed {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public string strFromImdok;
        
        public SetPrognosisToFixed() {
        }
        
        public SetPrognosisToFixed(string strFromImdok) {
            this.strFromImdok = strFromImdok;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetPrognosisToFixed_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class SetPrognosisToFixed_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public int return_value;
        
        public SetPrognosisToFixed_Result() {
        }
        
        public SetPrognosisToFixed_Result(int return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePrognosisCC", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class UpdatePrognosisCC {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public string strFromImdok;
        
        public UpdatePrognosisCC() {
        }
        
        public UpdatePrognosisCC(string strFromImdok) {
            this.strFromImdok = strFromImdok;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePrognosisCC_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class UpdatePrognosisCC_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public int return_value;
        
        public UpdatePrognosisCC_Result() {
        }
        
        public UpdatePrognosisCC_Result(int return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessIPS", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class ProcessIPS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=1)]
        public string key1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=2)]
        public string key2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=3)]
        public string key3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=4)]
        public string value1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=5)]
        public string value2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=6)]
        public string value3;
        
        public ProcessIPS() {
        }
        
        public ProcessIPS(int id, string key1, string key2, string key3, string value1, string value2, string value3) {
            this.id = id;
            this.key1 = key1;
            this.key2 = key2;
            this.key3 = key3;
            this.value1 = value1;
            this.value2 = value2;
            this.value3 = value3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessIPS_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class ProcessIPS_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public int return_value;
        
        public ProcessIPS_Result() {
        }
        
        public ProcessIPS_Result(int return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReleaseHourAcc", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class ReleaseHourAcc {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public string inputString;
        
        public ReleaseHourAcc() {
        }
        
        public ReleaseHourAcc(string inputString) {
            this.inputString = inputString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReleaseHourAcc_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class ReleaseHourAcc_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public string return_value;
        
        public ReleaseHourAcc_Result() {
        }
        
        public ReleaseHourAcc_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateSubProjectFromMainProject", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class CreateSubProjectFromMainProject {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public string inputString;
        
        public CreateSubProjectFromMainProject() {
        }
        
        public CreateSubProjectFromMainProject(string inputString) {
            this.inputString = inputString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateSubProjectFromMainProject_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class CreateSubProjectFromMainProject_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public string return_value;
        
        public CreateSubProjectFromMainProject_Result() {
        }
        
        public CreateSubProjectFromMainProject_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePriceToInvoiceInJob", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class UpdatePriceToInvoiceInJob {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public string inputString;
        
        public UpdatePriceToInvoiceInJob() {
        }
        
        public UpdatePriceToInvoiceInJob(string inputString) {
            this.inputString = inputString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePriceToInvoiceInJob_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class UpdatePriceToInvoiceInJob_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public string return_value;
        
        public UpdatePriceToInvoiceInJob_Result() {
        }
        
        public UpdatePriceToInvoiceInJob_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateSalesPriceByWageComponent", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class UpdateSalesPriceByWageComponent {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public string inputString;
        
        public UpdateSalesPriceByWageComponent() {
        }
        
        public UpdateSalesPriceByWageComponent(string inputString) {
            this.inputString = inputString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateSalesPriceByWageComponent_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class UpdateSalesPriceByWageComponent_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public string return_value;
        
        public UpdateSalesPriceByWageComponent_Result() {
        }
        
        public UpdateSalesPriceByWageComponent_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUpdatePrincipalContactPerson", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class CreateUpdatePrincipalContactPerson {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public string inputString;
        
        public CreateUpdatePrincipalContactPerson() {
        }
        
        public CreateUpdatePrincipalContactPerson(string inputString) {
            this.inputString = inputString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUpdatePrincipalContactPerson_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class CreateUpdatePrincipalContactPerson_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public string return_value;
        
        public CreateUpdatePrincipalContactPerson_Result() {
        }
        
        public CreateUpdatePrincipalContactPerson_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddProjDokToProforma", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class AddProjDokToProforma {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public string inputString;
        
        public AddProjDokToProforma() {
        }
        
        public AddProjDokToProforma(string inputString) {
            this.inputString = inputString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddProjDokToProforma_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class AddProjDokToProforma_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public string return_value;
        
        public AddProjDokToProforma_Result() {
        }
        
        public AddProjDokToProforma_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateEmployee", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class UpdateEmployee {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public string inputString;
        
        public UpdateEmployee() {
        }
        
        public UpdateEmployee(string inputString) {
            this.inputString = inputString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateEmployee_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", IsWrapped=true)]
    public partial class UpdateEmployee_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ImdokWS", Order=0)]
        public string return_value;
        
        public UpdateEmployee_Result() {
        }
        
        public UpdateEmployee_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImdokWS_PortChannel : Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImdokWS_PortClient : System.ServiceModel.ClientBase<Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port>, Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port {
        
        public ImdokWS_PortClient() {
        }
        
        public ImdokWS_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImdokWS_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImdokWS_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImdokWS_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePictureCount_Result Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.GetInvoicePictureCount(Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePictureCount request) {
            return base.Channel.GetInvoicePictureCount(request);
        }
        
        public int GetInvoicePictureCount(string no) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePictureCount inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePictureCount();
            inValue.no = no;
            Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePictureCount_Result retVal = ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).GetInvoicePictureCount(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePictureCount_Result> Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.GetInvoicePictureCountAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePictureCount request) {
            return base.Channel.GetInvoicePictureCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePictureCount_Result> GetInvoicePictureCountAsync(string no) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePictureCount inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePictureCount();
            inValue.no = no;
            return ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).GetInvoicePictureCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePicture_Result Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.GetInvoicePicture(Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePicture request) {
            return base.Channel.GetInvoicePicture(request);
        }
        
        public bool GetInvoicePicture(string no, int pictureIndex, ref string picture) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePicture inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePicture();
            inValue.Body = new Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePictureBody();
            inValue.Body.no = no;
            inValue.Body.pictureIndex = pictureIndex;
            inValue.Body.picture = picture;
            Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePicture_Result retVal = ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).GetInvoicePicture(inValue);
            picture = retVal.Body.picture;
            return retVal.Body.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePicture_Result> Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.GetInvoicePictureAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePicture request) {
            return base.Channel.GetInvoicePictureAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePicture_Result> GetInvoicePictureAsync(string no, int pictureIndex, string picture) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePicture inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePicture();
            inValue.Body = new Assemblin.BizTalk.InvoDAL.ImdokWS.GetInvoicePictureBody();
            inValue.Body.no = no;
            inValue.Body.pictureIndex = pictureIndex;
            inValue.Body.picture = picture;
            return ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).GetInvoicePictureAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assemblin.BizTalk.InvoDAL.ImdokWS.CreatePrognosisCC_Result Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.CreatePrognosisCC(Assemblin.BizTalk.InvoDAL.ImdokWS.CreatePrognosisCC request) {
            return base.Channel.CreatePrognosisCC(request);
        }
        
        public int CreatePrognosisCC(string strFromImdok) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.CreatePrognosisCC inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.CreatePrognosisCC();
            inValue.strFromImdok = strFromImdok;
            Assemblin.BizTalk.InvoDAL.ImdokWS.CreatePrognosisCC_Result retVal = ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).CreatePrognosisCC(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.CreatePrognosisCC_Result> Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.CreatePrognosisCCAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.CreatePrognosisCC request) {
            return base.Channel.CreatePrognosisCCAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.CreatePrognosisCC_Result> CreatePrognosisCCAsync(string strFromImdok) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.CreatePrognosisCC inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.CreatePrognosisCC();
            inValue.strFromImdok = strFromImdok;
            return ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).CreatePrognosisCCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assemblin.BizTalk.InvoDAL.ImdokWS.SetPrognosisToFixed_Result Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.SetPrognosisToFixed(Assemblin.BizTalk.InvoDAL.ImdokWS.SetPrognosisToFixed request) {
            return base.Channel.SetPrognosisToFixed(request);
        }
        
        public int SetPrognosisToFixed(string strFromImdok) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.SetPrognosisToFixed inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.SetPrognosisToFixed();
            inValue.strFromImdok = strFromImdok;
            Assemblin.BizTalk.InvoDAL.ImdokWS.SetPrognosisToFixed_Result retVal = ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).SetPrognosisToFixed(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.SetPrognosisToFixed_Result> Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.SetPrognosisToFixedAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.SetPrognosisToFixed request) {
            return base.Channel.SetPrognosisToFixedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.SetPrognosisToFixed_Result> SetPrognosisToFixedAsync(string strFromImdok) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.SetPrognosisToFixed inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.SetPrognosisToFixed();
            inValue.strFromImdok = strFromImdok;
            return ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).SetPrognosisToFixedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePrognosisCC_Result Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.UpdatePrognosisCC(Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePrognosisCC request) {
            return base.Channel.UpdatePrognosisCC(request);
        }
        
        public int UpdatePrognosisCC(string strFromImdok) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePrognosisCC inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePrognosisCC();
            inValue.strFromImdok = strFromImdok;
            Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePrognosisCC_Result retVal = ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).UpdatePrognosisCC(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePrognosisCC_Result> Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.UpdatePrognosisCCAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePrognosisCC request) {
            return base.Channel.UpdatePrognosisCCAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePrognosisCC_Result> UpdatePrognosisCCAsync(string strFromImdok) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePrognosisCC inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePrognosisCC();
            inValue.strFromImdok = strFromImdok;
            return ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).UpdatePrognosisCCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assemblin.BizTalk.InvoDAL.ImdokWS.ProcessIPS_Result Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.ProcessIPS(Assemblin.BizTalk.InvoDAL.ImdokWS.ProcessIPS request) {
            return base.Channel.ProcessIPS(request);
        }
        
        public int ProcessIPS(int id, string key1, string key2, string key3, string value1, string value2, string value3) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.ProcessIPS inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.ProcessIPS();
            inValue.id = id;
            inValue.key1 = key1;
            inValue.key2 = key2;
            inValue.key3 = key3;
            inValue.value1 = value1;
            inValue.value2 = value2;
            inValue.value3 = value3;
            Assemblin.BizTalk.InvoDAL.ImdokWS.ProcessIPS_Result retVal = ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).ProcessIPS(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.ProcessIPS_Result> Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.ProcessIPSAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.ProcessIPS request) {
            return base.Channel.ProcessIPSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.ProcessIPS_Result> ProcessIPSAsync(int id, string key1, string key2, string key3, string value1, string value2, string value3) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.ProcessIPS inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.ProcessIPS();
            inValue.id = id;
            inValue.key1 = key1;
            inValue.key2 = key2;
            inValue.key3 = key3;
            inValue.value1 = value1;
            inValue.value2 = value2;
            inValue.value3 = value3;
            return ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).ProcessIPSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assemblin.BizTalk.InvoDAL.ImdokWS.ReleaseHourAcc_Result Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.ReleaseHourAcc(Assemblin.BizTalk.InvoDAL.ImdokWS.ReleaseHourAcc request) {
            return base.Channel.ReleaseHourAcc(request);
        }
        
        public string ReleaseHourAcc(string inputString) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.ReleaseHourAcc inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.ReleaseHourAcc();
            inValue.inputString = inputString;
            Assemblin.BizTalk.InvoDAL.ImdokWS.ReleaseHourAcc_Result retVal = ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).ReleaseHourAcc(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.ReleaseHourAcc_Result> Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.ReleaseHourAccAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.ReleaseHourAcc request) {
            return base.Channel.ReleaseHourAccAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.ReleaseHourAcc_Result> ReleaseHourAccAsync(string inputString) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.ReleaseHourAcc inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.ReleaseHourAcc();
            inValue.inputString = inputString;
            return ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).ReleaseHourAccAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assemblin.BizTalk.InvoDAL.ImdokWS.CreateSubProjectFromMainProject_Result Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.CreateSubProjectFromMainProject(Assemblin.BizTalk.InvoDAL.ImdokWS.CreateSubProjectFromMainProject request) {
            return base.Channel.CreateSubProjectFromMainProject(request);
        }
        
        public string CreateSubProjectFromMainProject(string inputString) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.CreateSubProjectFromMainProject inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.CreateSubProjectFromMainProject();
            inValue.inputString = inputString;
            Assemblin.BizTalk.InvoDAL.ImdokWS.CreateSubProjectFromMainProject_Result retVal = ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).CreateSubProjectFromMainProject(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.CreateSubProjectFromMainProject_Result> Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.CreateSubProjectFromMainProjectAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.CreateSubProjectFromMainProject request) {
            return base.Channel.CreateSubProjectFromMainProjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.CreateSubProjectFromMainProject_Result> CreateSubProjectFromMainProjectAsync(string inputString) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.CreateSubProjectFromMainProject inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.CreateSubProjectFromMainProject();
            inValue.inputString = inputString;
            return ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).CreateSubProjectFromMainProjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePriceToInvoiceInJob_Result Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.UpdatePriceToInvoiceInJob(Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePriceToInvoiceInJob request) {
            return base.Channel.UpdatePriceToInvoiceInJob(request);
        }
        
        public string UpdatePriceToInvoiceInJob(string inputString) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePriceToInvoiceInJob inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePriceToInvoiceInJob();
            inValue.inputString = inputString;
            Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePriceToInvoiceInJob_Result retVal = ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).UpdatePriceToInvoiceInJob(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePriceToInvoiceInJob_Result> Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.UpdatePriceToInvoiceInJobAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePriceToInvoiceInJob request) {
            return base.Channel.UpdatePriceToInvoiceInJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePriceToInvoiceInJob_Result> UpdatePriceToInvoiceInJobAsync(string inputString) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePriceToInvoiceInJob inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.UpdatePriceToInvoiceInJob();
            inValue.inputString = inputString;
            return ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).UpdatePriceToInvoiceInJobAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateSalesPriceByWageComponent_Result Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.UpdateSalesPriceByWageComponent(Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateSalesPriceByWageComponent request) {
            return base.Channel.UpdateSalesPriceByWageComponent(request);
        }
        
        public string UpdateSalesPriceByWageComponent(string inputString) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateSalesPriceByWageComponent inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateSalesPriceByWageComponent();
            inValue.inputString = inputString;
            Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateSalesPriceByWageComponent_Result retVal = ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).UpdateSalesPriceByWageComponent(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateSalesPriceByWageComponent_Result> Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.UpdateSalesPriceByWageComponentAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateSalesPriceByWageComponent request) {
            return base.Channel.UpdateSalesPriceByWageComponentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateSalesPriceByWageComponent_Result> UpdateSalesPriceByWageComponentAsync(string inputString) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateSalesPriceByWageComponent inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateSalesPriceByWageComponent();
            inValue.inputString = inputString;
            return ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).UpdateSalesPriceByWageComponentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assemblin.BizTalk.InvoDAL.ImdokWS.CreateUpdatePrincipalContactPerson_Result Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.CreateUpdatePrincipalContactPerson(Assemblin.BizTalk.InvoDAL.ImdokWS.CreateUpdatePrincipalContactPerson request) {
            return base.Channel.CreateUpdatePrincipalContactPerson(request);
        }
        
        public string CreateUpdatePrincipalContactPerson(string inputString) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.CreateUpdatePrincipalContactPerson inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.CreateUpdatePrincipalContactPerson();
            inValue.inputString = inputString;
            Assemblin.BizTalk.InvoDAL.ImdokWS.CreateUpdatePrincipalContactPerson_Result retVal = ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).CreateUpdatePrincipalContactPerson(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.CreateUpdatePrincipalContactPerson_Result> Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.CreateUpdatePrincipalContactPersonAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.CreateUpdatePrincipalContactPerson request) {
            return base.Channel.CreateUpdatePrincipalContactPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.CreateUpdatePrincipalContactPerson_Result> CreateUpdatePrincipalContactPersonAsync(string inputString) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.CreateUpdatePrincipalContactPerson inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.CreateUpdatePrincipalContactPerson();
            inValue.inputString = inputString;
            return ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).CreateUpdatePrincipalContactPersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assemblin.BizTalk.InvoDAL.ImdokWS.AddProjDokToProforma_Result Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.AddProjDokToProforma(Assemblin.BizTalk.InvoDAL.ImdokWS.AddProjDokToProforma request) {
            return base.Channel.AddProjDokToProforma(request);
        }
        
        public string AddProjDokToProforma(string inputString) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.AddProjDokToProforma inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.AddProjDokToProforma();
            inValue.inputString = inputString;
            Assemblin.BizTalk.InvoDAL.ImdokWS.AddProjDokToProforma_Result retVal = ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).AddProjDokToProforma(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.AddProjDokToProforma_Result> Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.AddProjDokToProformaAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.AddProjDokToProforma request) {
            return base.Channel.AddProjDokToProformaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.AddProjDokToProforma_Result> AddProjDokToProformaAsync(string inputString) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.AddProjDokToProforma inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.AddProjDokToProforma();
            inValue.inputString = inputString;
            return ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).AddProjDokToProformaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateEmployee_Result Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.UpdateEmployee(Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateEmployee request) {
            return base.Channel.UpdateEmployee(request);
        }
        
        public string UpdateEmployee(string inputString) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateEmployee inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateEmployee();
            inValue.inputString = inputString;
            Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateEmployee_Result retVal = ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).UpdateEmployee(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateEmployee_Result> Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port.UpdateEmployeeAsync(Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateEmployee request) {
            return base.Channel.UpdateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateEmployee_Result> UpdateEmployeeAsync(string inputString) {
            Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateEmployee inValue = new Assemblin.BizTalk.InvoDAL.ImdokWS.UpdateEmployee();
            inValue.inputString = inputString;
            return ((Assemblin.BizTalk.InvoDAL.ImdokWS.ImdokWS_Port)(this)).UpdateEmployeeAsync(inValue);
        }
    }
}
